# Written by Jae Woo Lee
# This Makefile should be used as a template for future Makefiles.
# It’s heavily commented, so hopefully you can understand what each
# line does.

# We’ll use gcc for C compilation and g++ for C++ compilation

CC  = gcc
CXX = g++

INCLUDES =

CFLAGS   = -g -Wall $(INCLUDES)
CXXFLAGS = -g -Wall $(INCLUDES)

LDFLAGS = -g

LDLIBS =

heap_example: 

heap_example.o:

struct_example:

struct_example.o:

function_pointer_example:

function_pointer_example.o:

.PHONY: clean
clean:
	rm -f *.o a.out core heap_example struct_example function_pointer_example


.PHONY: all
all: clean heap_example struct_example function_pointer_example
